# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahdhc_members',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.Department'),
        ),
        migrations.AlterField(
            model_name='audit_trail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='college_id',
            field=models.ForeignKey(db_column='college_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.College'),
        ),
        migrations.AlterField(
            model_name='respondents',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.Department'),
        ),
        migrations.AlterField(
            model_name='univ_reps',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.Department'),
        ),
    ]
