# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170329_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases_ahdhc_members',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
