# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170329_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases_hearings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cases_misconducts_respondents',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
