# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170330_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconducts',
            name='csc_section',
            field=models.TextField(max_length=100),
        ),
    ]
