# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20170418_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases_ahdhc_members',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.ahdhc_members'),
        ),
        migrations.AlterField(
            model_name='cases_misconducts_respondents',
            name='misconduct_id',
            field=models.ForeignKey(db_column='misconduct_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.Misconducts'),
        ),
        migrations.AlterField(
            model_name='cases_misconducts_respondents',
            name='respondent_id',
            field=models.ForeignKey(db_column='respondent_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.Respondents'),
        ),
    ]
