# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20170428_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases_hearings',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
