# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170501_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='respondednt_answer_date',
            new_name='respondent_answer_date',
        ),
    ]
