# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20170501_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='adhdc_constitution_deadline',
            new_name='ahdhc_constitution_deadline',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
