# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20170502_0106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Misconducts',
            new_name='Misconduct',
        ),
        migrations.RenameModel(
            old_name='Respondents',
            new_name='Respondent',
        ),
        migrations.RenameModel(
            old_name='univ_reps',
            new_name='univ_rep',
        ),
    ]
